version: '3.0'

volumes:
  postgres-data:

services:
  pgdb:
    image: postgres
    env_file: "hh_ru_django/config.env"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8888
    volumes:
      - .:/usr/src/hh_ru_django
    ports:
      - "8888:8888"
    env_file: "hh_ru_django/config.env"
    depends_on:
      - pgdb
      - redis
      - celery
  celery:
    build: .
    command: celery -A hh_ru_django worker --beat --broker=redis://redis:6379/0 --concurrency=2
    volumes:
      - .:/usr/src/hh_ru_django
    env_file: "hh_ru_django/config.env"
    depends_on:
      - node1
      - node2
  flower: # нужен для отслеживания задач celery при помощи графического интерфейса
    build: .
    command: flower -A hh_ru_django --beat --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5555:5555
    env_file: "hh_ru_django/config.env"
    depends_on:
      - django
  node1:  # это движок chrome для selenium
    image: selenium/node-chrome:4.0.0-beta-1-20210215
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    env_file: "hh_ru_django/config.env"
  node2:  # это движок chrome для selenium
    image: selenium/node-chrome:4.0.0-beta-1-20210215
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    env_file: "hh_ru_django/config.env"
  selenium-hub:  # это агрегатор движков Selenium
    image: selenium/hub:4.0.0-beta-1-20210215
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
  redis:
    image: redis:6.0.10
    ports:
      - '6379:6379'
