version: '3.0'

volumes:
  postgres-data:

services:
  pgdb:
    image: postgres:13
    env_file: "hh_ru_django/config.env"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: always
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8888
    volumes:
      - .:/usr/src/hh_ru_django
    ports:
      - "8888:8888"
    env_file: .env
    depends_on:
      - pgdb
      - redis
      - celery
    restart: always
  celery:
    build: 
      context: .
      dockerfile: Dockerfile
    command: celery -A hh_ru_django worker --beat --broker=redis://redis:6379/0 --concurrency=2
    volumes:
      - .:/usr/src/hh_ru_django
    env_file: "hh_ru_django/config.env"
    restart: always
  flower: # нужен для отслеживания задач celery при помощи графического интерфейса
    build: .
    command: flower -A hh_ru_django --beat --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5555:5555
    env_file: "hh_ru_django/config.env"
    depends_on:
      - django
    restart: always
  redis: # Брокер для Celery
    image: redis:6.0.10
    ports:
      - '6379:6379'
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    working_dir: /var/lib/redis
    restart: always
  chrome:
    image: selenium/standalone-chrome:latest
    hostname: chrome
    ports:
      - "5900:5900"
      - "4444:4444"
    privileged: true
    shm_size: 2g
    restart: always