# Generated by Django 3.1.6 on 2021-05-12 10:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=128)),
                ('company_name', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=64)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('work_experience', models.CharField(blank=True, max_length=64, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=48, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('vacancy_url', models.CharField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('state', models.CharField(default='normal', max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
