# Generated by Django 3.1.6 on 2021-02-14 16:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False)),
                ('modified_date', models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False)),
                ('title', models.CharField(max_length=64)),
                ('company_name', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=32)),
                ('work_experience', models.CharField(max_length=20)),
                ('employment_type', models.CharField(max_length=32)),
                ('schedule', models.CharField(max_length=16)),
                ('description', models.TextField()),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ads_ad_related_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ads_ad_related_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
