# Generated by Django 3.1.6 on 2021-03-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='city',
            field=models.CharField(max_length=64),
        ),
    ]
