# Generated by Django 3.1.6 on 2021-02-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20210214_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='city',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='ad',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='employment_type',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name='ad',
            name='phone',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='vacancy_url',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='work_experience',
            field=models.CharField(max_length=64),
        ),
    ]
