# Generated by Django 3.1.6 on 2021-03-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20210302_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='company_name',
            field=models.CharField(max_length=64),
        ),
    ]
